/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Diagnostics */
        get: operations["liveness_probe_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness Probe */
        get: operations["readiness_probe_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard KPI metrics
         * @description Returns customer-facing configuration metrics for the dashboard.
         */
        get: operations["get_dashboard_metrics_api_v1_dashboard_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configurations/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search configurations
         * @description Case-insensitive search by project name, display ID, or configuration ID.
         */
        get: operations["search_configurations_api_v1_configurations_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configurations */
        get: operations["list_configurations_api_v1_configurations_get"];
        put?: never;
        /** Create a new configuration */
        post: operations["create_configuration_api_v1_configurations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configurations/{configuration_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get configuration */
        get: operations["get_configuration_api_v1_configurations__configuration_id__get"];
        /** Update configuration */
        put: operations["update_configuration_api_v1_configurations__configuration_id__put"];
        post?: never;
        /** Delete configuration */
        delete: operations["delete_configuration_api_v1_configurations__configuration_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configurations/{configuration_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run validation pipeline */
        post: operations["validate_configuration_api_v1_configurations__configuration_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configurations/{configuration_id}/pricing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pricing summary */
        get: operations["get_configuration_pricing_api_v1_configurations__configuration_id__pricing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configurations/{configuration_id}/validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get validation results */
        get: operations["get_configuration_validation_api_v1_configurations__configuration_id__validation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configurations/{configuration_id}/bom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get bill of materials */
        get: operations["get_configuration_bom_api_v1_configurations__configuration_id__bom_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Pipeline Diagnostics
         * @description Returns deep diagnostic information about the core configuration pipeline.
         */
        get: operations["system_pipeline_api_v1_system_pipeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Store Diagnostics
         * @description Returns lightweight diagnostic information about the active configuration store.
         */
        get: operations["store_diagnostics_api_v1_system_store_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configurations/{configuration_id}/export/{format_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Configuration
         * @description Generates a read-only export of the requested configuration.
         */
        get: operations["export_configuration_api_v1_configurations__configuration_id__export__format_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configurations/{configuration_id}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve Quote Information
         * @description Retrieve quote metadata and summary (read-only).
         */
        get: operations["get_quote_info_api_v1_configurations__configuration_id__quote_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List elevator categories
         * @description Returns all active elevator categories available for selection.
         */
        get: operations["list_categories_api_v1_catalogue_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List features
         * @description Returns all configurable features grouped by their feature group.
         */
        get: operations["list_features_api_v1_catalogue_features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/feature-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List feature options
         * @description Returns all selectable feature options. Each option belongs to a feature.
         */
        get: operations["list_feature_options_api_v1_catalogue_feature_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List feature dependencies
         * @description Returns rules for feature incompatibilities (EXCLUDES).
         */
        get: operations["list_dependencies_api_v1_catalogue_dependencies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * APISuccessEnvelope
         * @description Standardized API Success Response Envelope.
         */
        APISuccessEnvelope: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data: unknown;
            /** Correlation Id */
            correlation_id?: string | null;
            /** Timestamp */
            timestamp: string;
        };
        /**
         * CreateConfigurationRequest
         * @description Payload for starting a new configuration session.
         */
        CreateConfigurationRequest: {
            /**
             * Project Name
             * @description Customer-given project name (e.g. 'My Apartment')
             */
            project_name: string;
            /**
             * Customer Name
             * @description Project-in Charge / Customer Name
             */
            customer_name?: string | null;
            /**
             * Selected Category
             * @description The chosen ElevatorCategory ID
             */
            selected_category?: string | null;
            /**
             * Customer Reference
             * @description Deprecated: Optional CRM/ERP reference ID
             */
            customer_reference?: string | null;
        };
        /**
         * DetailedHealthResponse
         * @description Detailed diagnostics combining data and engine state.
         */
        DetailedHealthResponse: {
            status: components["schemas"]["HealthStatus"];
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Data Initialized */
            data_initialized: boolean;
            /** Data Files */
            data_files?: {
                [key: string]: boolean;
            };
            /** Pipeline Ready */
            pipeline_ready: boolean;
            /** Engine Reports */
            engine_reports?: unknown[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @enum {string}
         */
        HealthStatus: "healthy" | "degraded" | "unhealthy";
        /**
         * ReadinessResponse
         * @description Simple readiness probe.
         */
        ReadinessResponse: {
            status: components["schemas"]["HealthStatus"];
            /** Ready */
            ready: boolean;
        };
        /** RuntimeMetrics */
        RuntimeMetrics: {
            /** Uptime Seconds */
            uptime_seconds: number;
            /**
             * Total Requests Processed
             * @default 0
             */
            total_requests_processed: number;
            /**
             * Pipeline Executions
             * @default 0
             */
            pipeline_executions: number;
        };
        /** StartupMetrics */
        StartupMetrics: {
            /** Application Startup Duration Ms */
            application_startup_duration_ms: number;
            /** Repository Initialization Ms */
            repository_initialization_ms: number;
            /** Registry Initialization Ms */
            registry_initialization_ms: number;
            /** Pipeline Initialization Ms */
            pipeline_initialization_ms: number;
        };
        /**
         * SystemPipelineResponse
         * @description Pipeline diagnostic info.
         */
        SystemPipelineResponse: {
            /** Registered Engines */
            registered_engines: string[];
            /** Catalogue Version */
            catalogue_version: string;
            /** Schema Version */
            schema_version: string;
            /** Startup Timestamp */
            startup_timestamp: string;
            /** Ready */
            ready: boolean;
            startup_metrics: components["schemas"]["StartupMetrics"];
            runtime_metrics: components["schemas"]["RuntimeMetrics"];
        };
        /**
         * UpdateConfigurationRequest
         * @description Payload for updating an existing configuration.
         */
        UpdateConfigurationRequest: {
            /**
             * Project Name
             * @description Update project name
             */
            project_name?: string | null;
            /**
             * Customer Name
             * @description Update customer name
             */
            customer_name?: string | null;
            /**
             * Selected Feature Options
             * @description IDs of selected FeatureOptions
             */
            selected_feature_options?: string[] | null;
            /**
             * Selected Category
             * @description The chosen ElevatorCategory ID
             */
            selected_category?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_probe_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedHealthResponse"];
                };
            };
        };
    };
    readiness_probe_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    get_dashboard_metrics_api_v1_dashboard_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APISuccessEnvelope"];
                };
            };
        };
    };
    search_configurations_api_v1_configurations_search_get: {
        parameters: {
            query?: {
                /** @description Search term */
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APISuccessEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_configurations_api_v1_configurations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APISuccessEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_configuration_api_v1_configurations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConfigurationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APISuccessEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_configuration_api_v1_configurations__configuration_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APISuccessEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_configuration_api_v1_configurations__configuration_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConfigurationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APISuccessEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_configuration_api_v1_configurations__configuration_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_configuration_api_v1_configurations__configuration_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APISuccessEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_configuration_pricing_api_v1_configurations__configuration_id__pricing_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APISuccessEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_configuration_validation_api_v1_configurations__configuration_id__validation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APISuccessEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_configuration_bom_api_v1_configurations__configuration_id__bom_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APISuccessEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_pipeline_api_v1_system_pipeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemPipelineResponse"];
                };
            };
        };
    };
    store_diagnostics_api_v1_system_store_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    export_configuration_api_v1_configurations__configuration_id__export__format_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Configuration ID */
                configuration_id: string;
                /** @description json, pdf, excel */
                format_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quote_info_api_v1_configurations__configuration_id__quote_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Configuration ID */
                configuration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_v1_catalogue_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APISuccessEnvelope"];
                };
            };
        };
    };
    list_features_api_v1_catalogue_features_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APISuccessEnvelope"];
                };
            };
        };
    };
    list_feature_options_api_v1_catalogue_feature_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APISuccessEnvelope"];
                };
            };
        };
    };
    list_dependencies_api_v1_catalogue_dependencies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APISuccessEnvelope"];
                };
            };
        };
    };
}
